name: Build KDU
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build KDU
        run: msbuild Source/kdu.sln /p:Configuration=Release /p:Platform=x64
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: KDU-Binary
          path: "**/*.exe"
